#GET {{content_host}}/content/course-category/tree-nodes

POST {{content_host}}/content/course
Content-Type: application/json

{
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "niewf",
  "teachmode": "200002",
  "users": "≥ıº∂»À‘±",
  "tags": "fuydr",
  "grade": "284081",
  "description": "fydsrt",
  "charge": "201001",
  "price": 5,
  "originalprice": 10,
  "qq": "11111111",
  "wechat": "111111",
  "phone": "11111111",
  "validDays": 365
}